/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    LinkComponent: typeof import('./src/components/LinkComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UptimeRobotComponent: typeof import('./src/components/UptimeRobotComponent.vue')['default']
  }
}
